
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: pytest -q
workflows:
  version: 2
  main:
    jobs:
      - build
